#用户的公开文章
query userArticlesQuery(
    $user_id: Int,
    $submit:ArticleSubmitStatus, 
    $status: ArticleStatus, 
    $category_id: Int
) {
    articles(
        submit: $submit
        user_id: $user_id
        status: $status
        category_id: $category_id
    ) {
        paginatorInfo {
            hasMorePages
            currentPage
        }
        data {
            id
            type
            body
            description
            time_ago
            cover
            hits
            count_likes
            count_replies
            count_tips
            liked
            submit
            answered_status
            question_reward
            user {
                avatar
                name
                id
            }
            categories {
                id
                name
                logo
            }
            images {
                id
                url
                width
                height
            }
            video {
                id
                url
                duration
                info {
                    width
                    height
                    rotate
                    covers
                }
                cover_url
            }
        }
    }
}