query CategoriesQuery($filter: CategoryFilter, $first: Int, $page: Int) {
  categories(filter: $filter, first: $first, page: $page) {
    data {
      id
      logo
      name
      count_articles
    }
  }
}
