# 置顶的推荐合集
query recommendCollectionsQuery {
    recommendCollections {
        topCover
        topCollection {
            id
            logo
            name
            description
            followed
            user {
                id
                name
            }
            count_views
            updated_to_episode
        }
        recommendCollectionsA {
            id
            logo
            name
            description
            followed
            user {
                id
                name
            }
            count_views
            updated_to_episode
        }
        recommendCollectionsB {
            id
            logo
            name
            description
            followed
            user {
                id
                name
            }
            count_views
            updated_to_episode
        }
    }
}
