query typeCollectionsQuery($user_id:Int,$type:CollectionEnum){
  typeCollections(user_id:$user_id,type:$type){
    paginatorInfo{
      hasMorePages
      currentPage
      total
    }
    data{
      id
      description
      name
      logo
      posts{
        paginatorInfo{
          hasMorePages
          currentPage
          total
        }data{
          id
          description
          video{
            id
            url
            cover
            cover_url
          }
        }
      }
    }
  }
}