query issues($orderBy: [QueryIssuesOrderByOrderByClause!]) {
    issues(orderBy: $orderBy) {
        paginatorInfo {
            hasMorePages
            currentPage
        }
        data {
            title
            background
            count_answers
            created_at
            updated_at
            id
        }
    }
}
