# 搜索合集
query searchCollectionsQuery($query: String!, $page: Int, $first: Int) {
    searchCollections(query: $query, page: $page, first: $first) {
        paginatorInfo {
            currentPage
            hasMorePages
        }
        data {
            id
            logo
            name
            count_articles
            count_follows
            count_posts
            count_views
            updated_to_episode
            followed
            type
            status
            user {
                id
                name
            }
        }
    }
}
